feat(Meme.ts): Redo NSFW filter
CryptonDev/Crypton pull request #4
Opened 2021-07-22 09:17 UTC by Megatank58

2021-07-22 09:28 UTC, khiromoshito commented on src/commands/fun/meme.ts
>  	}
The recursive is unnecessary, but it's fine.

2021-07-22 09:34 UTC, Megatank58 commented on src/commands/fun/meme.ts
>  	}
It is to make sure that the meme is always sfw if both memes are nsfw this will rerun to make sure that the user only gets sfw memes

2021-07-22 09:36 UTC, khiromoshito commented on src/commands/fun/meme.ts
>  	}
Yes, carry on.

2021-07-22 09:49 UTC, khiromoshito requested changes
This is good, just resolve the linter build fails and you're good to go.

2021-07-23 11:24 UTC, parthasarath1 commented
use a subreddit where there are no nsfw memes, property nsfw is not correct always

2021-07-24 04:25 UTC, Megatank58 commented
Closing since now we have a better option

2021-07-24 04:25 UTC, closed without merging