warn commands, voice ranking setup
CryptonDev/Crypton pull request #5
Opened 2021-07-23 11:22 UTC by parthasarath1

2021-07-23 13:07 UTC, khiromoshito commented on src/utils/functions.ts
> +export function generateRandomString(length:number) {
This blew my brain out. 

Man, is the entropy thing really necessary? In the end, it still ends up fetching characters from A-z0-9. This whole function can be shortened to less than 10 lines with less endeavors.

2021-07-23 13:10 UTC, khiromoshito commented on src/utils/embeds.ts
> +	deleteMessage(errorMessage, 3000);
3 seconds is probably too short, especially with users of unstable connection? Probably 7 - 10 would do just fine.

You can also make a default value for this so you wouldn't have to set them individually in the future (?)

And by the way, I like the way that you put common embeds into a single place. Nice move.

2021-07-23 13:15 UTC, parthasarath1 commented on src/utils/embeds.ts
> +	deleteMessage(errorMessage, 3000);
all cooldowns are copied from dyno 😂 | I will make a global variable which holds all cooldowns, so all can be changed at once

2021-07-23 13:16 UTC, parthasarath1 commented on src/utils/functions.ts
> +export function generateRandomString(length:number) {
This function copied from a popular package, 'uuid' , will change to a shorter one in next PR

2021-07-23 13:21 UTC, khiromoshito commented on src/commands/Moderation/warn.ts
> +		}
PROTIP: Whenever there's some group of actions, it is good practice to put them in a separate function. It's the `S` (single responsibility)  in the `SOLID design patterns` which means *"putting different responsibilities in independent places"*. This will make the function less clunky, more readable, and easily manageable.

For example, all these if statements that check for invalid command actions can all be moved into a function called, let's say, `validateCommand(message)`. This will apply to every code base you work on. : )

2021-07-23 13:27 UTC, parthasarath1 commented on src/commands/Moderation/warn.ts
> +		}
Thats a good Idea, will do it, we can talk on discord

2021-07-24 02:57 UTC, Megatank58 commented on src/utils/embeds.ts
> +	deleteMessage(errorMessage, 3000);
3 seconds is fine, people with unstable connection will get it late and it will be deleted late for them

2021-07-24 03:06 UTC, Megatank58 requested changes

2021-07-24 03:06 UTC, Megatank58 commented on src/commands/tools/steal.ts
> +	}
This is same as ping command

2021-07-24 03:06 UTC, Megatank58 commented on src/listeners/voiceStateUpdate.ts
> +}
Put voiceRanking in same file as a static function

2021-07-24 03:06 UTC, Megatank58 commented on src/utils/classes/VoiceRanking.ts
> +	}
make this a static function in the same file

2021-07-24 03:48 UTC, Megatank58 approved these changes

2021-07-24 03:49 UTC, merged