new comments and a new command
CryptonDev/Crypton pull request #6
Opened 2021-07-24 06:42 UTC by vedadub

Roast and new lines for older fun commands

2021-07-24 06:46 UTC, Megatank58 requested changes

2021-07-24 06:46 UTC, Megatank58 commented on src/commands/fun/epicgamerrate.ts
>  			name: '8ball',
Name is still same

2021-07-25 00:15 UTC, khiromoshito commented on src/commands/fun/8ball.ts
>  		const answer = answers[Math.floor(Math.random() * answers.length)];
Since you've been using index randomizer frequently, you should just make it a util method, like `pickFromArray`.

2021-07-25 04:41 UTC, Megatank58 reviewed
LGTM

2021-07-25 04:43 UTC, Megatank58 approved these changes

2021-07-25 04:43 UTC, merged